backend:
  name: git-gateway
  branch: main

local_backend: true

media_folder: "src/images/uploads"
public_folder: "/images/uploads"

site_url: https://alphabad83.fr
display_url: https://alphabad83.fr
logo_url: /images/favicon.svg

locale: "fr"

collections:
  - name: "reglages"
    label: "Réglages du club"
    files:
      - name: "club"
        label: "Informations générales"
        file: "src/_data/club.json"
        fields:
          - { label: "Nom du club", name: "nom", widget: "string" }
          - { label: "Logo (image carrée de préférence)", name: "logo", widget: "image", required: false }
          - { label: "Nom complet (association)", name: "nomLong", widget: "string" }
          - { label: "Accroche", name: "accroche", widget: "string" }
          - { label: "Description courte (page d'accueil)", name: "descriptionCourte", widget: "text" }
          - { label: "E-mail de contact", name: "email", widget: "string" }
          - { label: "Téléphone", name: "telephone", widget: "string" }
          - { label: "Adresse postale", name: "adressePostale", widget: "string" }
          - label: "Communes du canton"
            name: "villes"
            widget: "list"
          - label: "Réseaux sociaux"
            name: "reseaux"
            widget: "object"
            fields:
              - { label: "Facebook (lien complet)", name: "facebook", widget: "string", required: false }
              - { label: "Instagram (lien complet)", name: "instagram", widget: "string", required: false }
              - { label: "Discord (lien complet)", name: "discord", widget: "string", required: false }
          - { label: "Lien d'adhésion en ligne (si existant)", name: "adhesionUrl", widget: "string", required: false }
          - { label:
